Repository eclipse-platform/eclipse.platform, pull requests merged in 2024-06, with the labels that each got.

#1403 Pin inspect
  debug/org.eclipse.debug.ui/ui/org/eclipse/debug/ui/DebugPopup.java
Labels: enhancement, noteworthy

#1436 add API for IFile.readNBytes(n)
  resources/bundles/org.eclipse.core.resources/src/org/eclipse/core/resources/IFile.java
  resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/IFileTest.java
Labels: enhancement, api

#1445 [performance] IFile.create: reduce 1 of 3 store.fetchInfo()
  resources/bundles/org.eclipse.core.resources/src/org/eclipse/core/internal/localstore/FileSystemResourceManager.java
  resources/bundles/org.eclipse.core.resources/src/org/eclipse/core/internal/resources/File.java
Labels: performance

#1446 [performance] IFile.write(byte[]): reduce store.fetchInfo()
  resources/bundles/org.eclipse.core.resources/src/org/eclipse/core/internal/localstore/FileSystemResourceManager.java
  resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/IFileTest.java
Labels: performance
