Repository eclipse-platform/eclipse.platform, pull requests merged in 2025-02, with the labels that each got.

#1720 [performance] Avoid O(n^2) in DeadlockDetector.lockAcquired()
  runtime/bundles/org.eclipse.core.jobs/src/org/eclipse/core/internal/jobs/DeadlockDetector.java
Labels: performance

#1730 try to fix Random failing NatureTest.testBug297871 #1688
  resources/bundles/org.eclipse.core.resources/src/org/eclipse/core/internal/localstore/FileSystemResourceManager.java
  resources/bundles/org.eclipse.core.resources/src/org/eclipse/core/internal/resources/ProjectDescription.java
  resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/NatureTest.java
Labels: test

#1725 Feature request: Extend `AbstractSearchProcessor#postSearch(...)` of the `org.eclipse.help.searchProcessor` extension point
  ua/org.eclipse.help.base/src/org/eclipse/help/internal/search/SearchResults.java
  ua/org.eclipse.help.base/src/org/eclipse/help/internal/search/federated/LocalHelp.java
  ua/org.eclipse.help.base/src/org/eclipse/help/search/AbstractSearchProcessor.java
  ua/org.eclipse.help.webapp/src/org/eclipse/help/internal/webapp/data/SearchData.java
  ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/search/AllSearchTests.java
  ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/search/SearchProcessorTest.java
  ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/search/WrappedSearchProcessor.java
  ua/org.eclipse.ua.tests/plugin.xml
Labels: enhancement
